name: Notify Downstream Projects
on:
    push:
        branches: [develop]
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {} # We use ELEMENT_BOT_TOKEN instead
jobs:
    notify-downstream:
        # Only respect triggers from our develop branch, ignore that of forks
        if: github.repository == 'matrix-org/matrix-js-sdk'
        continue-on-error: true
        strategy:
            fail-fast: false
            matrix:
                include:
                    - repo: element-hq/element-web
                      event: element-web-notify

        runs-on: ubuntu-24.04
        steps:
            - name: Notify matrix-react-sdk repo that a new SDK build is on develop so it can CI against it
              uses: peter-evans/repository-dispatch@5fc4efd1a4797ddb68ffd0714a238564e4cc0e6f # v4
              with:
                  token: ${{ secrets.ELEMENT_BOT_TOKEN }}
                  repository: ${{ matrix.repo }}
                  event-type: ${{ matrix.event }}
